-- Migration: Update default role permissions to match company configuration
-- Run this to update the create_default_company_roles function with new permission sets

CREATE OR REPLACE FUNCTION create_default_company_roles(p_company_id UUID, p_created_by UUID)
RETURNS VOID AS $$
BEGIN
  -- Admin Role (44/44 permissions - Full access)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'admin',
    'Admin',
    'Company owner/administrator with full access to all features',
    true,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', true,
      'can_create_leads', true,
      'can_edit_leads', true,
      'can_delete_leads', true,
      'can_view_all_leads', true,
      'can_view_quotes', true,
      'can_create_quotes', true,
      'can_edit_quotes', true,
      'can_delete_quotes', true,
      'can_approve_quotes', true,
      'can_send_quotes', true,
      'can_view_invoices', true,
      'can_create_invoices', true,
      'can_edit_invoices', true,
      'can_delete_invoices', true,
      'can_record_payments', true,
      'can_void_payments', true,
      'can_view_material_orders', true,
      'can_create_material_orders', true,
      'can_edit_material_orders', true,
      'can_delete_material_orders', true,
      'can_mark_orders_paid', true,
      'can_view_work_orders', true,
      'can_create_work_orders', true,
      'can_edit_work_orders', true,
      'can_delete_work_orders', true,
      'can_assign_crew', true,
      'can_view_customers', true,
      'can_create_customers', true,
      'can_edit_customers', true,
      'can_delete_customers', true,
      'can_view_financials', true,
      'can_view_profit_margins', true,
      'can_view_commission_reports', true,
      'can_export_reports', true,
      'can_view_users', true,
      'can_create_users', true,
      'can_edit_users', true,
      'can_delete_users', true,
      'can_manage_permissions', true,
      'can_edit_company_settings', true,
      'can_upload_photos', true,
      'can_update_project_status', true,
      'can_view_project_timeline', true
    )
  );

  -- Office Staff Role (42/44 permissions)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'office',
    'Office Staff',
    'Office staff managing quotes, invoices, customers, and scheduling',
    false,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', true,
      'can_create_leads', true,
      'can_edit_leads', true,
      'can_delete_leads', true,
      'can_view_all_leads', true,
      'can_view_quotes', true,
      'can_create_quotes', true,
      'can_edit_quotes', true,
      'can_delete_quotes', true,
      'can_approve_quotes', true,
      'can_send_quotes', true,
      'can_view_invoices', true,
      'can_create_invoices', true,
      'can_edit_invoices', true,
      'can_delete_invoices', true,
      'can_record_payments', true,
      'can_void_payments', true,
      'can_view_material_orders', true,
      'can_create_material_orders', true,
      'can_edit_material_orders', true,
      'can_delete_material_orders', true,
      'can_mark_orders_paid', true,
      'can_view_work_orders', true,
      'can_create_work_orders', true,
      'can_edit_work_orders', true,
      'can_delete_work_orders', true,
      'can_assign_crew', true,
      'can_view_customers', true,
      'can_create_customers', true,
      'can_edit_customers', true,
      'can_delete_customers', true,
      'can_view_financials', true,
      'can_view_profit_margins', true,
      'can_view_commission_reports', true,
      'can_export_reports', true,
      'can_view_users', true,
      'can_create_users', true,
      'can_edit_users', true,
      'can_delete_users', false, -- Office can't delete users
      'can_manage_permissions', true,
      'can_edit_company_settings', false, -- Office can't edit company settings
      'can_upload_photos', true,
      'can_update_project_status', true,
      'can_view_project_timeline', true
    )
  );

  -- Sales Manager Role (35/44 permissions)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'sales_manager',
    'Sales Manager',
    'Sales team lead managing sales reps and overseeing all leads',
    false,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', true,
      'can_create_leads', true,
      'can_edit_leads', true,
      'can_delete_leads', true,
      'can_view_all_leads', true,
      'can_view_quotes', true,
      'can_create_quotes', true,
      'can_edit_quotes', true,
      'can_delete_quotes', true,
      'can_approve_quotes', true,
      'can_send_quotes', true,
      'can_view_invoices', true,
      'can_create_invoices', false,
      'can_edit_invoices', false,
      'can_delete_invoices', false,
      'can_record_payments', false,
      'can_void_payments', false,
      'can_view_material_orders', true,
      'can_create_material_orders', true,
      'can_edit_material_orders', true,
      'can_delete_material_orders', true,
      'can_mark_orders_paid', false,
      'can_view_work_orders', true,
      'can_create_work_orders', true,
      'can_edit_work_orders', true,
      'can_delete_work_orders', true,
      'can_assign_crew', false,
      'can_view_customers', true,
      'can_create_customers', true,
      'can_edit_customers', true,
      'can_delete_customers', false,
      'can_view_financials', true,
      'can_view_profit_margins', true,
      'can_view_commission_reports', true,
      'can_export_reports', true,
      'can_view_users', true,
      'can_create_users', false,
      'can_edit_users', false,
      'can_delete_users', false,
      'can_manage_permissions', false,
      'can_edit_company_settings', false,
      'can_upload_photos', true,
      'can_update_project_status', true,
      'can_view_project_timeline', true
    )
  );

  -- Sales Representative Role (32/44 permissions)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'sales',
    'Sales Rep',
    'Sales representative managing assigned leads and creating quotes',
    false,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', true,
      'can_create_leads', true,
      'can_edit_leads', true,
      'can_delete_leads', false,
      'can_view_all_leads', false,
      'can_view_quotes', true,
      'can_create_quotes', true,
      'can_edit_quotes', true,
      'can_delete_quotes', true,
      'can_approve_quotes', false,
      'can_send_quotes', true,
      'can_view_invoices', true,
      'can_create_invoices', true,
      'can_edit_invoices', true,
      'can_delete_invoices', false,
      'can_record_payments', false,
      'can_void_payments', false,
      'can_view_material_orders', true,
      'can_create_material_orders', true,
      'can_edit_material_orders', true,
      'can_delete_material_orders', true,
      'can_mark_orders_paid', false,
      'can_view_work_orders', true,
      'can_create_work_orders', true,
      'can_edit_work_orders', true,
      'can_delete_work_orders', true,
      'can_assign_crew', false,
      'can_view_customers', true,
      'can_create_customers', true,
      'can_edit_customers', true,
      'can_delete_customers', false,
      'can_view_financials', true,
      'can_view_profit_margins', true,
      'can_view_commission_reports', true,
      'can_export_reports', false,
      'can_view_users', true,
      'can_create_users', false,
      'can_edit_users', false,
      'can_delete_users', false,
      'can_manage_permissions', false,
      'can_edit_company_settings', false,
      'can_upload_photos', true,
      'can_update_project_status', true,
      'can_view_project_timeline', true
    )
  );

  -- Production/Crew Role (17/44 permissions)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'production',
    'Production/Crew',
    'Production crew members updating work orders and project status',
    false,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', true,
      'can_create_leads', false,
      'can_edit_leads', false,
      'can_delete_leads', false,
      'can_view_all_leads', false,
      'can_view_quotes', true,
      'can_create_quotes', false,
      'can_edit_quotes', false,
      'can_delete_quotes', false,
      'can_approve_quotes', false,
      'can_send_quotes', false,
      'can_view_invoices', false,
      'can_create_invoices', false,
      'can_edit_invoices', false,
      'can_delete_invoices', false,
      'can_record_payments', false,
      'can_void_payments', false,
      'can_view_material_orders', true,
      'can_create_material_orders', true,
      'can_edit_material_orders', true,
      'can_delete_material_orders', true,
      'can_mark_orders_paid', false,
      'can_view_work_orders', true,
      'can_create_work_orders', true,
      'can_edit_work_orders', true,
      'can_delete_work_orders', true,
      'can_assign_crew', true,
      'can_view_customers', true,
      'can_create_customers', false,
      'can_edit_customers', false,
      'can_delete_customers', false,
      'can_view_financials', false,
      'can_view_profit_margins', false,
      'can_view_commission_reports', false,
      'can_export_reports', false,
      'can_view_users', false,
      'can_create_users', false,
      'can_edit_users', false,
      'can_delete_users', false,
      'can_manage_permissions', false,
      'can_edit_company_settings', false,
      'can_upload_photos', true,
      'can_update_project_status', true,
      'can_view_project_timeline', true
    )
  );

  -- Marketing Role (15/44 permissions)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'marketing',
    'Marketing',
    'Marketing team creating campaigns and analyzing lead performance',
    false,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', true,
      'can_create_leads', true,
      'can_edit_leads', true,
      'can_delete_leads', false,
      'can_view_all_leads', false,
      'can_view_quotes', true,
      'can_create_quotes', false,
      'can_edit_quotes', false,
      'can_delete_quotes', false,
      'can_approve_quotes', false,
      'can_send_quotes', true,
      'can_view_invoices', true,
      'can_create_invoices', false,
      'can_edit_invoices', false,
      'can_delete_invoices', false,
      'can_record_payments', false,
      'can_void_payments', false,
      'can_view_material_orders', false,
      'can_create_material_orders', false,
      'can_edit_material_orders', false,
      'can_delete_material_orders', false,
      'can_mark_orders_paid', false,
      'can_view_work_orders', false,
      'can_create_work_orders', false,
      'can_edit_work_orders', false,
      'can_delete_work_orders', false,
      'can_assign_crew', false,
      'can_view_customers', true,
      'can_create_customers', true,
      'can_edit_customers', true,
      'can_delete_customers', false,
      'can_view_financials', false,
      'can_view_profit_margins', false,
      'can_view_commission_reports', false,
      'can_export_reports', false,
      'can_view_users', true,
      'can_create_users', false,
      'can_edit_users', false,
      'can_delete_users', false,
      'can_manage_permissions', false,
      'can_edit_company_settings', false,
      'can_upload_photos', false,
      'can_update_project_status', true,
      'can_view_project_timeline', true
    )
  );

  -- Customer Portal Role (2/44 permissions)
  INSERT INTO company_roles (company_id, role_name, display_name, description, is_system_role, created_by, permissions)
  VALUES (
    p_company_id,
    'customer',
    'Customer Role',
    'This role is for the customer portal',
    false,
    p_created_by,
    jsonb_build_object(
      'can_view_leads', false,
      'can_create_leads', false,
      'can_edit_leads', false,
      'can_delete_leads', false,
      'can_view_all_leads', false,
      'can_view_quotes', true,
      'can_create_quotes', false,
      'can_edit_quotes', false,
      'can_delete_quotes', false,
      'can_approve_quotes', false,
      'can_send_quotes', false,
      'can_view_invoices', true,
      'can_create_invoices', false,
      'can_edit_invoices', false,
      'can_delete_invoices', false,
      'can_record_payments', false,
      'can_void_payments', false,
      'can_view_material_orders', false,
      'can_create_material_orders', false,
      'can_edit_material_orders', false,
      'can_delete_material_orders', false,
      'can_mark_orders_paid', false,
      'can_view_work_orders', false,
      'can_create_work_orders', false,
      'can_edit_work_orders', false,
      'can_delete_work_orders', false,
      'can_assign_crew', false,
      'can_view_customers', false,
      'can_create_customers', false,
      'can_edit_customers', false,
      'can_delete_customers', false,
      'can_view_financials', false,
      'can_view_profit_margins', false,
      'can_view_commission_reports', false,
      'can_export_reports', false,
      'can_view_users', false,
      'can_create_users', false,
      'can_edit_users', false,
      'can_delete_users', false,
      'can_manage_permissions', false,
      'can_edit_company_settings', false,
      'can_upload_photos', false,
      'can_update_project_status', false,
      'can_view_project_timeline', false
    )
  );
END;
$$ LANGUAGE plpgsql;

-- Add comment explaining the permission counts
COMMENT ON FUNCTION create_default_company_roles IS 'Creates 7 default roles with specific permission sets: Admin (44/44), Office (42/44), Sales Manager (35/44), Sales (32/44), Production (17/44), Marketing (15/44), Customer (2/44)';
